'use client'

import { motion } from 'framer-motion'
import { Star, Quote } from 'lucide-react'

const testimonials = [
  {
    name: 'Arjun Mehta',
    role: 'Software Engineer @ Google',
    avatar: 'AM',
    color: 'from-blue-500 to-cyan-600',
    rating: 5,
    quote:
      'ResumeAI helped me tailor my resume for each Google interview round. The ATS score went from 68% to 94% in minutes. Got the offer!',
  },
  {
    name: 'Priya Sharma',
    role: 'Data Scientist @ Microsoft',
    avatar: 'PS',
    color: 'from-purple-500 to-violet-600',
    rating: 5,
    quote:
      'The AI extracted skills from my projects that I didn\'t even think to include. My profile was automatically 3x more complete.',
  },
  {
    name: 'Rahul Kumar',
    role: 'Product Manager @ Stripe',
    avatar: 'RK',
    color: 'from-emerald-500 to-teal-600',
    rating: 5,
    quote:
      'I applied to 20 companies with 20 different tailored resumes, all generated by ResumeAI. Got 14 callbacks. This platform is incredible.',
  },
  {
    name: 'Ananya Singh',
    role: 'ML Engineer @ Meta',
    avatar: 'AS',
    color: 'from-orange-500 to-rose-600',
    rating: 5,
    quote:
      'The gap analysis feature showed me exactly what skills to learn for my target role. And the resume templates look gorgeous.',
  },
  {
    name: 'Dev Patel',
    role: 'Frontend Engineer @ Vercel',
    avatar: 'DP',
    color: 'from-indigo-500 to-blue-600',
    rating: 5,
    quote:
      'Best investment in my career. Compared to Teal and Enhancv, ResumeAI is in a completely different league for AI capability.',
  },
  {
    name: 'Sneha Reddy',
    role: 'DevOps Engineer @ AWS',
    avatar: 'SR',
    color: 'from-pink-500 to-rose-600',
    rating: 5,
    quote:
      'As a fresher, I had no idea how to write impact-driven bullets. ResumeAI transformed my plain descriptions into powerful statements.',
  },
]

export function Testimonials() {
  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8 surface-1">
      <div className="mx-auto max-w-7xl">
        <div className="text-center mb-16">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="heading-display text-4xl md:text-5xl text-foreground mb-4"
          >
            Trusted by job seekers
            <br />
            <span className="gradient-text">who landed offers</span>
          </motion.h2>
          <motion.p
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-muted-foreground"
          >
            From fresh graduates to senior engineers — see what they say.
          </motion.p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {testimonials.map((t, i) => (
            <motion.div
              key={t.name}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.07 }}
              className="premium-card p-6 space-y-4"
            >
              <div className="flex items-start justify-between">
                <Quote size={24} className="text-primary/30" />
                <div className="flex gap-0.5">
                  {Array.from({ length: t.rating }).map((_, i) => (
                    <Star key={i} size={14} className="fill-amber-400 text-amber-400" />
                  ))}
                </div>
              </div>
              <p className="text-sm text-foreground leading-relaxed">&ldquo;{t.quote}&rdquo;</p>
              <div className="flex items-center gap-3 pt-2 border-t border-border">
                <div
                  className={`flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br ${t.color} text-white text-xs font-bold shrink-0`}
                >
                  {t.avatar}
                </div>
                <div>
                  <p className="text-sm font-semibold text-foreground">{t.name}</p>
                  <p className="text-xs text-muted-foreground">{t.role}</p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
